### ISSUE TITLE
Update of maven repositories

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#105]
Current we use the configuration in [the wiki](https://github.com/glygener/glygen-array-backend/wiki/Maven-repositories).

Long term it would be good to harmonize this.

**Comment by ReneRanzinger** [comment]
Hello René,

We used to set up and operate our own Maven repository (https://nexus.glycoinfo.org/). 
This server is maintained and operated at Soka University. 
However, the operation and management of this server have increased 
in difficulty and we are looking into other ways of operating and managing 
for contents of this Maven repository server. In the future, 
we would like to shut down the Maven repository server at Soka University.

Currently, WURCSFramework was in the process of migrating 
from https://glycoinfo.gitlab.io/wurcsframework 
to https://gitlab.com/glycoinfo/wurcsframework/-/packages 
The following is a summary of the project.

We apologize for not sharing this information 
with you as we were also in the process of reviewing it.

We are considering using the GLIC mailing list 
to share information on these considerations in the future.

Also, we have changed the README of 
the GLIC (https://github.com/glycoinfo/MavenRepository) 
from Japanese to English, so please point out any oddities or edit it directly.

We are continuing to review the list to make it easier for everyone to use.
If you have any good ideas, we would be grateful if you could let us know.

The changelog for WURCSFramework and Glycanbuilder2 can be found 
in each project. It would be useful if there is a system 
that allows easy checking of other software as well.

  WFW: https://gitlab.com/glycoinfo/wurcsframework (Release note in README)
  GB2: https://github.com/glycoinfo/GlycanBuilder2/blob/master/CHANGELOG.md

```
It would also be good to know where the current source code repository 
for these jars is – that will certainly help in debugging.
```

This is a good idea, I would like to add this to 
the GLIC website (https://glic.glycoinfo.org/software/).

We hope you find these information useful.

Best,
Issaku

**Comment by ReneRanzinger** [comment]
Hi   René,

The "Github Meaven repository (GLIC repository)" mainly contains tools 
from the EuroCarb project. 
The reason is that Deploy is more complicated than in GitLab.

Many of the tools we are currently developing, such as 
WURCSFramework and GlycanFormatConverter, 
are maintained in Gitlab, which is easier to Deploy 
and therefore better suited for frequent updates.

Indeed, it would be more efficient for users to consolidate 
in one repository, so we could consider registering 
in a "maven central repository", 
but we don't currently have the time to do so.

Also, as mentioned above, GlycanFormatConverter is maintained at Gitlab.

You can use the latest version here:
https://gitlab.com/glycoinfo/glycanformatconverter/-/packages

Here is the update history:
https://gitlab.com/glycoinfo/glycanformatconverter/-/blob/master/CHANGELOG.md

Thanks,
Issaku

**Comment by ReneRanzinger** [comment]
@senaarpinar It seems the repository for WURCSframework is going to change to https://gitlab.com/glycoinfo/wurcsframework/-/packages. And the location for glycanformatconverter is already changed to https://gitlab.com/glycoinfo/glycanformatconverter/-/packages.

**Comment by senaarpinar** [comment]
I have updated wurcframework, glycanformatconverter and glycanbuilder to the latest versions and updated the maven repositories accordingly.

I haven't changed the location of molecularframework and resourcesdb jars. They are in our Nexus repository (generated from GRITS plugins)
