### ISSUE TITLE
License on dataset page

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#111]
**On the public view dataset page**
In the same column as the "Submitter" box, beside the "Summary" box add another box under "Submitter":
```
"License"
Creative Commons Attribution 4.0 International 
(CC BY 4.0) 
Logo
```
Copy the [creative commons logo](https://www.glygen.org/static/media/CreativeCommons_logo_trademark.4b09d8ce.svg) into the frontend. Logo and "Creative Commons Attribution 4.0 International " and logo are links to: https://creativecommons.org/licenses/by/4.0/

**Comment by senaarpinar** [comment]
done but "summary" and the next column do not have the same height now. @ReneRanzinger How should I arrange these?

**Comment by ReneRanzinger** [comment]
Can you deploy it send a screenshot?

**Comment by senaarpinar** [comment]
deployed now on the server

**Comment by ReneRanzinger** [comment]
hmm I can not see it when I go to one of the datasets.

**Comment by senaarpinar** [comment]
may need to force reloading of the page. 

<img width="1759" alt="Screen Shot 2023-08-01 at 4 56 49 PM" src="https://github.com/glygener/glygen-array-backend/assets/8181316/3e749e3e-3acb-4f10-8274-26c9086bb477">

**Comment by senaarpinar** [comment]
Like this?

<img width="1569" alt="Screen Shot 2023-08-01 at 5 05 36 PM" src="https://github.com/glygener/glygen-array-backend/assets/8181316/590866e1-f028-48c8-a44e-405c31e3c8cb">

**Comment by ReneRanzinger** [comment]
Looks good.
