### ISSUE TITLE
License information when making public

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#112]
When the user makes a dataset public have an information dialog pop up. Dialog headline "License information". Dialog content: 
```
When releasing datasets to the public all information will be accessible under the Creative Commons  Attribution 4.0 International (CC BY 4.0). Users can freely access, share and adapt the data. But are required to give appropriate credit.

Detailed information on the license can be found here.
```
The dialog has an "Accept" (OK) and "Decline" (Cancel) button. The "here" in the last sentence links to: https://creativecommons.org/licenses/by/4.0/

**Comment by senaarpinar** [comment]
done
