### ISSUE TITLE
Public slide page

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#115]
Related to #114. The name of the slide in the table is a link to this page. For this page we treat Slide Layout as the same as the slide.

Summary box in the beginning of the page:
* Name
* Dimensions (see #114 )
* Printer metadata (just the name that is a link to the metadata dialog)
* Print run metadata  (just the name that is a link to the metadata dialog)
* Slide metadata ((just the name that is a link to the metadata dialog)
* Description

Slide Layout box
* Display of the graphical grid
* Click on cell in the grid opens a dialog with the grid for the blocklayout + feature information section

On top of the page is a Download feature for
* Extended Gal file (submitted) - if present
* Extended Gal file

**Comment by senaarpinar** [comment]
added to the server
