### ISSUE TITLE
Problem with sorting glycan table

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#117]
1. Search by glycan Mass : 2770-4502
2. go to page 3
3. change number of rows to 50
4. Sort by Dataset count (one click) - lots of "0"
5. Sort by Dataset count (one click) - Starts with "988" and later lots of "0"
6. Now go to page 2 = all "0" again

Might not be a problem with the sorting by rather that after 3. we are on the "wrong" page.

**Comment by senaarpinar** [comment]
server-side pagination on the react table implementation had some issues. The page count/size etc. seem to be updated on the table frontend but the data is always the first batch from the server when the page size changes. Fixed it in dataset table, slide table and glygen table (which is used everywhere else when there is server-side pagination) but there seems to be a react issue that triggers the fetch of the data twice and sometimes (mostly the dataset table) the wrong page is displayed.

**Comment by senaarpinar** [comment]
I fixed the problem in a different way, due to the loading of the table twice. When the page size is changed, the table goes back to the first page. I believe this is the expected behaviour of the table anyway since all the pagination examples I found online are behaving that way.
