### ISSUE TITLE
Missing RepoID in data export

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#119]
https://glygen.ccrc.uga.edu/ggarray/data/dataset/AD9984716 

* Go to Data section
* Selected Processed data
* Right side click download (choose export)
* Open the Excel file
* Second column (RepoID) is null

**Comment by senaarpinar** [comment]
duplicate of #56 and #64. @ReneRanzinger this would be fixed when we re-upload the datasets.
