### ISSUE TITLE
Data download (JSON) for metadata - public interface

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#122]
When displaying the metadata in the public interface we should have download options (JSON):
* Display of individual metadata 
* Display of all metadata in addition to the excel export (all-in-one)

This JSON should be importable in the submission interface. When importing the all-in-one file as printer metadata it should just extract the printer metadata and create a new one but ignore the rest.

A potential option for the all-in-one file could be
```
{
   "pinter": {
      ...
   },
   "print-run": {
      ...
   },
   ...
}
```

In all downloads we should have a top-level version attribute. Similar to GRITS different versions may have to trigger different processing moving forward.

**Comment by senaarpinar** [comment]
implemented the download. creating a new ticket for "import"
