### ISSUE TITLE
Cross accounting between array and ggarray

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#128]
I am logged out on array and ggarray. 
* Go to ggarray and login with cfgdata
* Go to array => Iam logged in.

**Comment by senaarpinar** [comment]
we are using window.localstorage and it is shared between pages within the same domain. "ggarray" and "array" are part of the same domain so the token is shared. We may want to append basename to the variables (token and loggedinuser) stored in window.localstorage to prevent cross sharing.

**Comment by senaarpinar** [comment]
added baseurl to the variables used for login/logout. Cross referencing should not occur now. We need to test all contribute pages since this change affects all.
