### ISSUE TITLE
Glycan details - General section size and image

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#130]
For [glycan details](https://glygen.ccrc.uga.edu/ggarray/glycanDetail/3862081GAR) page:
* Make the general section the same width as the datasets and slides section
* Use the full size image in the general section

**Comment by senaarpinar** [comment]
@ReneRanzinger This has the same style as  [slide details](https://glygen.ccrc.uga.edu/ggarray/slideList/slidelayout/PS8830567) and [user datasets](https://glygen.ccrc.uga.edu/ggarray/data/userDatasets/cfgdata) pages. Should I change those to have the full length as well?

**Comment by ReneRanzinger** [comment]
Yes, lets use it everywhere, even though we will not need the additional space for the users page.

**Comment by senaarpinar** [comment]
Changed these three pages to have the full size section at the top
