### ISSUE TITLE
DRS java client code

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#132]
We need to talk how far your DRS test code (client) is reusable. Does it have a option to take a DRS uri and give me the URL (or the information object containing the URL)?

**Comment by ReneRanzinger** [comment]
As discussed today. Make an own repository in the glygener organization. "glygen-drs-client" for example. Add the DRS object model there and add a Java class that performs the request. Input to the method in the class is a DRS URI. Response is the object with the file metadata including the URI or an exception with an HTTP code and response from the server. Also add a maven build to make a jar out of this. We should probably add it to our maven repository. I leave it to you if you want to use the jar in array backend or leave a copy of the object model in there.

**Comment by senaarpinar** [comment]
created the drs client  [repository](https://github.com/glygener/glygen-drs-client)
and added the jar file to nexus repository

@ReneRanzinger could you please have a look and let me know if any changes are necessary

**Comment by ReneRanzinger** [comment]
There is a problem with the indirect dependencies see [here](https://github.com/glygener/glygen-drs-client/issues/1)
