### ISSUE TITLE
DRS URIs

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#133]
Are the following URIs valid. Can you test a few with any of the clients?

drs://glygen.ccrc.uga.edu/1671659988718
drs://glygen.ccrc.uga.edu/1671659988909
drs://glygen.ccrc.uga.edu/1671668772717
drs://glygen.ccrc.uga.edu/1671668772923
drs://glygen.ccrc.uga.edu/1671670233764
drs://glygen.ccrc.uga.edu/1671670234021
drs://glygen.ccrc.uga.edu/1672424961734
drs://glygen.ccrc.uga.edu/1671514989437
drs://glygen.ccrc.uga.edu/1671514989617
drs://glygen.ccrc.uga.edu/1671673220778
drs://glygen.ccrc.uga.edu/1671673220972
drs://glygen.ccrc.uga.edu/1671752154376
drs://glygen.ccrc.uga.edu/1671752154556
drs://glygen.ccrc.uga.edu/1671591778193
drs://glygen.ccrc.uga.edu/1671591778419
drs://glygen.ccrc.uga.edu/1671823131017
drs://glygen.ccrc.uga.edu/1671823131217
drs://glygen.ccrc.uga.edu/1671603498458
drs://glygen.ccrc.uga.edu/1671603498623

**Comment by senaarpinar** [comment]
most of these URIs are not valid since the files were stored in the repository without their DRS ids. It is not possible to locate them without DRS id in the repository. I can write some code to add those triples ("file->drsid") to the repository for all the existing files to solve this problem without regenerating all the data.

**Comment by senaarpinar** [comment]
@ReneRanzinger I updated the triple store and tested most of the above DRS URIs. They all work now.

**Comment by senaarpinar** [comment]
if you'd like to test using the DRS web service, you can use the following URL:

https://glygen.ccrc.uga.edu/ggarray/api/ga4gh/drs/v1/objects/1671603498623/access/1671603498623 (for the last entry as an example)

**Comment by ReneRanzinger** [comment]
@senaarpinar that URL will give an error when used as GET. I guess I will have to set the media type in the request header. Should we change the servers to assume a default or is that a requirement by the specs?
