### ISSUE TITLE
Database ERD for Array

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#134]
Use [DbVisualizer](https://www.dbvis.com/download/) or any other tools you prefer create an ERD of the PostgreSQL database of the array backend. If you need help with DbVisualizer, let me know.

**Comment by senaarpinar** [comment]
Here is the ER diagram
![postgresER](https://github.com/glygener/glygen-array-backend/assets/8181316/72a9689b-0cba-4927-b2d7-1d194e2a2d16)
