### ISSUE TITLE
Unknown error when creating a new expeirment - cfg data user

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#146]
![Screenshot 2024-01-18 at 5 43 35 PM](https://github.com/glygener/glygen-array-backend/assets/2267640/800a0f74-10ca-4abe-9af0-999c91aa5ad3)

**Comment by ReneRanzinger** [comment]
happens with other users as well.

**Comment by senaarpinar** [comment]
I believe I found the issue and fixed it. @ReneRanzinger Can I update the server to test the fix?
