### ISSUE TITLE
Error pulling Glycan from GlyTouCan

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#147]
I tried creating a glycan from GlyTouCan and got this error. I think the issue is the GlycoCT sequence selection and the WURCS string. But after pulling the information both fields are disabled.
![Screenshot from 2024-02-01 00-55-28](https://github.com/glygener/glygen-array-backend/assets/2267640/c3fe36ea-ee65-4403-93fc-1cc08e7c069a)

**Comment by senaarpinar** [comment]
yes. that glycan cannot be converted to GlycoCT. We may other have issues for these kinds of glycans since we cannot determine the base type and other configurations without GlycoCT.

but the problem with the sequence type selection is fixed now.
