### ISSUE TITLE
Enlarge glycan images on click

### ISSUE THREAD

**Issue by senaarpinar** [glygener/glygen-array-backend#25]
Some large glycan images are not visible in the table columns. See the example image functionality of the website that is expected for glycan images.
![image](https://user-images.githubusercontent.com/8181316/203636606-beaf4cf0-2f7b-48ee-8f65-ae0ab0f6fc9f.png)

**Comment by senaarpinar** [comment]
open a dialog on click that shows the whole image, and has a close button.

**Comment by senaarpinar** [comment]
I have changed the cartoon display to have a horizontal scroll bar in case the image it too long for the cell. @ReneRanzinger is this ok?

**Comment by ReneRanzinger** [comment]
It would work but I still can not see the entire structure at once. Maybe we should make one of the columns a link to the glycan details page anyway. e.g. have the first column link to [glycan details](https://glygen.ccrc.uga.edu/ggarray/glycanDetail/3862081GAR)

**Comment by senaarpinar** [comment]
a zoom cursor (magnifying glass) is shown when hovering the image and on click, a modal dialog is shown:
![IMG_6235](https://github.com/glygener/glygen-array-backend/assets/8181316/1b55fbcc-00c7-40e7-9296-85bae319269d)

<img width="1220" alt="Screen Shot 2023-08-18 at 4 40 01 PM" src="https://github.com/glygener/glygen-array-backend/assets/8181316/9a1e39e8-c7c7-437b-90b7-fd97c14cc034">

Is this good?

**Comment by ReneRanzinger** [comment]
Looks good.

**Comment by senaarpinar** [comment]
added clickable zoom option when the images are inside a table column
