### ISSUE TITLE
Mass defined glycan changes

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#26]
Trying to add a mass defined glycan:

Page 2
* Replace “Glytoucan Id” with “GlyTouCan ID”
* What is the meaning of the tickbox. there is no label
* Replace sequence type with “Sequence Format”
* Limits, comment text field and reset button problem as in other pages (ADR-422) 
* Wait icon is only shown in top part of the screen when scrolled down

After a sequence was retrieved from GlyTouCan you should no longer be able to change it.

**Comment by senaarpinar** [comment]
This is not related to "mass defined glycans". 

The following still needs to be implemented:

- After a sequence was retrieved from GlyTouCan you should no longer be able to change it.
- Replace sequence type with “Sequence Format”

Not sure about this one: Wait icon is only shown in top part of the screen when scrolled down

**Comment by ReneRanzinger** [comment]
@senaarpinar Wait icon is shown in the middle of the page. But if it stays longer AND there is scrollbar it will scroll away rather than staying in the center of the page.

**Comment by senaarpinar** [comment]
confirmed that the wait icon scrolls down to the middle when scrolling down the page.
fixed the other 2 issues.
made sequence format disabled as well as the sequence field when the sequence is retrieved from glytoucan.
