### ISSUE TITLE
Add Glycan: what to do if glytoucan retrieval fails

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#34]
If the user adds a glycan by entering a glytoucan id and the sequence, the web service checks if the entered glytoucan matches the one retrieved from GlyToucan for the given sequence. If the glytoucan API fails to work (as it is happening now), we may not get the glytoucan id. The current implementation gives an error and does not allow addition of the glycan.

Is there any other alternatives for this case? Should we accept the glycan with the user’s entered information without confirming with the GlyToucan? Should we remove the glytoucan id entered and add the glycan without the glytoucan id? In this case, when/where the user can add a glytoucan id to an existing glycan when the Glytoucan API becomes available again.

**Comment by ReneRanzinger** [comment]
What is the current strategy for this?

**Comment by senaarpinar** [comment]
Current strategy is the one explained in the ticket. We have not made any recent changes to this behaviour.
