### ISSUE TITLE
Feedback option on all pages

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#51]
Add a feedback option on all pages similar to GlyGen. 

![Feedback-GlyGen](https://user-images.githubusercontent.com/2267640/225726607-5f83b82f-b8ec-4093-bd78-375bad56c1d8.png)

Feedback should be logged in the postgres database:
* id
* Type (problem, question, suggestion)
* Message
* Name
* Email

It should also trigger an email send to @senaarpinar and @ReneRanzinger.

**Comment by senaarpinar** [comment]
@ReneRanzinger I am sending this email to the admins (currently only my email is listed, I will add yours after the test phase). Any changes?

<img width="742" alt="Screen Shot 2023-08-16 at 12 28 14 PM" src="https://github.com/glygener/glygen-array-backend/assets/8181316/3174afa6-c209-43b7-a296-1ec8ca22bd16">

And this is the message to the user (who created the feedback):

<img width="723" alt="Screen Shot 2023-08-16 at 12 31 12 PM" src="https://github.com/glygener/glygen-array-backend/assets/8181316/00b2c1d1-d914-4c0d-9d6f-ecbb9388c4f0">

**Comment by ReneRanzinger** [comment]
@senaarpinar We also need the type of feedback, or is this the last word in the subject line? I would also copy the message body from the first email into the body of the second email (after the two sentences).

**Comment by senaarpinar** [comment]
@ReneRanzinger yes, the type is the last word in the subject.

**Comment by ReneRanzinger** [comment]
@senaarpinar ok, please add a "-" or ":" before it. Otherwise I will forget and ask the same question again ... In case we get ever feedback.

**Comment by senaarpinar** [comment]
Added. Changes should be on the server tomorrow. I also added @ReneRanzinger email to the list to receive the feedback
