### ISSUE TITLE
Dataset details: Processed data table misses standard deviation

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#55]
* Go to dataset details page
* Processed data => in Histogram the standard deviation is shown as error bars
* Click on Table => missing standard deviation

Standard deviation should be shown in the table as well. Either as own column or (to save space) as part of Intensity column (e.g. 99.64 +/- 10).

**Comment by senaarpinar** [comment]
added as ± in the rfu column
