### ISSUE TITLE
Dataset details: Export of processed data incomplete

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#56]
Example: https://glygen.ccrc.uga.edu/ggarray/data/dataset/AD9984716

* Go to "Data" section
* Select "Processed Data" node
* Download => "Export processed data"
* Open file
   * All RepoID columns a null it should show GlyTouCan IDs or repository IDs
   * What is ID column (just an autoincrement or is it linked to something?)

**Comment by senaarpinar** [comment]
same problem with the GAL file export issue #64. Public features lost their internal id. They would be regenerated once we upload the data again.
According to the [documentation](https://wiki.glygen.org/Glycan_array_data_repository/Processed_data_file), RepoID is the internal id of the feature, not the glycan. So I don't think we should expect glytoucanid in this field. 
ID column is an autoincrement.
