### ISSUE TITLE
Edit Blocklayout ends up on create block layout

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#58]
Account: cfgdata

* Contribute/Slide/Block layout
* Click on edit for CFG_V5.2-9
* It end up on an empty create block layout page

What kind of edits do we currently allow for block layouts? What happens if the layout is part of a public slide layout?

**Comment by senaarpinar** [comment]
retrieval of public block layouts (by id) were failing. Fixed the backend query.

@ReneRanzinger  We allow changing the name/description regardless of being public or not
