### ISSUE TITLE
Headlines for metadata should include metadata

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#60]
Go to Spot metadata. Current headline "Your Spots" that is misleading. It should say "Your Spot metadata". Same goes for the text line below the headline. 

Button should also say "Add Spot metadata" rather than "Add Spot".

On the wizard pages the same as above both for headline and description of the page.

The same applies to most other metadata pages as well.

**Comment by senaarpinar** [comment]
done
