### ISSUE TITLE
Hide dropdown on first metadata create page and edit page

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#61]
![Metadata dropdown](https://user-images.githubusercontent.com/2267640/226451171-de879eae-02fe-444d-acb2-a9e58b545dc9.png)

On most metadata creation and edit page that dropdown is meaningless. I think its only used for sample were we have a classifications. How is this populated? From the server? If yes lets check if there is only one element and hide the dropdown. The one possible value is than set to the metadata object by the default. If there are more values (sample) show the dropdown and let the user choose.

**Comment by senaarpinar** [comment]
implemented.
