### ISSUE TITLE
Metadata wizard pages dont scoll up automatically

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#62]
* Create a printer metadata object. 
* Fill all fields and scroll down to the buttons
* Submit
* Create a new metadata object (give name => Next)
* You are at the end of the page

That even works when creating one metadata and after this a different type of metadata. When going back and next between wizard pages it should always be at the top.

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni found a solution for this in GlyGen. I am not sure if it will work for us since the React version is different.

**Comment by senaarpinar** [comment]
@sujeetvkulkarni Can you point me to the code for this?

**Comment by senaarpinar** [comment]
The problem described in this ticket does not happen anymore. I could not reproduce it. But I fixed the issue for some other wizard pages (add feature). Next/Back will scroll to the top of the page.
