### ISSUE TITLE
Missing ID and RepoID in exported GAL file

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#64]
* Export a GAL file for a CFG slide layout.
* ID and RepoID columns are empty. Why?

**Comment by senaarpinar** [comment]
I tested this and ID column is populated for me. RepoID column is optional as far as I can remember. It is used to override the value in ID column. See [documentation](https://wiki.glygen.org/Extended_GAL_File#RepoID_(optional))

**Comment by senaarpinar** [comment]
ID is not working on the server since the features are already public and we were not transferring the internal id to the public graph. I've made the required code changes but we need to update the repository to be able to see the fix.
