### ISSUE TITLE
What is MIRAGE button in metadata overview tables

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#67]
Go to any metadata contribute page. In the table with the metadata elements, actions column is a MIRAGE button. What is it supposed to do? Clicking on it right now does not do anything.

**Comment by senaarpinar** [comment]
mirage button is supposed to check if the given metadata is mirage compliant. There was an error for metadata (other than Sample). Fixed. Also the message was not displayed on the page. Added a dialogue to show the results of mirage check. It lists all the missing descriptors.
