### ISSUE TITLE
Type and Value switched for Reference in Printrun/Printing condition

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#69]
* Create new printrun
* Fill first page => Next
* Go to Printing condition
* Click plus at the reference line
* Its not the same "Add Reference" Dialog as in other places. Here are several problems:
   * Type is a text field but should be a dropdown
   * Value is a dropdown but should be text
* When the dialog is finished with OK the values in the table are wrong.

Thinking about this now. Could that be the problem in #68 for the printrun line?

**Comment by senaarpinar** [comment]
they were listed incorrectly in the printrun spreadsheet. I fixed the spreadsheet but we need to repopulate the metadata in the server for this to be fixed
