### ISSUE TITLE
MIRAGE metadata export

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#70]
Have a download option on the [metadata page](https://glygen.ccrc.uga.edu/ggarray/data/dataset/AD5285063/metadata). Download format is an Excel file:
- Sheet 1: Hierarchical structure of the dataset 
   - we need to create short unique names that can be used as labels for the other sheets (e.g. Slide 1)
- All metadata objects get own sheets with the hierarchical element as prefix (e.g. Slide 1 - Printer; Slide 1 - Printrun)
- The metadata will be printed as table with 3 columns for the descriptors (hierarchical) and column D for the values
- Sheet 1: Also contains the Information of the dataset:
   - Name
   - Description
   - Dates
   - Keywords
   - Papers
- Sheet 1: Also contains a URL to the dataset page for this ID

**Comment by senaarpinar** [comment]
implemented the first version. added to the frontend for public and private experiments
