### ISSUE TITLE
Slide Layout Upload: It will be nicer to know which GlyTouCan ID was not matched 

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-backend#71]
**Is your feature request related to a problem? Please describe.**
When I tried to uploaded a slide layout from a xml file, I received an error message saying - "glytoucanId - NoMatch."
It will be great if you could display a bit more details, for example the meaning the 'No Match' or the glycan name which did not mathc etc.

**Page**
Slide Layout Upload

**Example Data**
[icl_lib_forDeposition+BKPyV2023.zip](https://github.com/glygener/glygen-array-frontend/files/11119571/icl_lib_forDeposition%2BBKPyV2023.zip)

Slide Layout Name: BKPyV_2023_1

**Comment by senaarpinar** [comment]
@yukie-a  I added the details to the error message. This error occurs when the entered glytoucanid is not the same as the one retrieved from Glytoucan.org for that sequence. The error message will now list the entered glytoucanid, retrieved glytoucanid and the name of the glycan where this occurred.
