### ISSUE TITLE
Not able to upload a new slide layout if there is a slide layout which is under 'processing' condition

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-backend#72]
**Describe the bug**
I tried to upload 8 new slide layouts. 
When I uploaded the first slide layout (e.g. MMC1-1), the upload status became 'proceeding'. (This is nice to see!)
I continued to upload the second slide layout (MMC1-2), and received an error message saying:
"File upload failed for following reasons:
An unidentified error has occurred. Please be patient while we investigate this."

**Page**
Slide Layout

**To Reproduce**
1. Go to 'Slide Layout'
2. Click on 'Add Slide Layour From File' and add a slide layout
4. After completing the slide layout, continue to the same process to upload the next slide layout

**Expected behavior**
Maybe... deactivate the 'submit' button when the uploading status of the previous slide layout is 'Processing'..?

**Comment by senaarpinar** [comment]
The error shown on the page is fixed and the "add slide layout from file" is disabled when there is an ongoing process.
