### ISSUE TITLE
Look into DRS (resolver service)

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#75]
Over the summer we will have to provide an implementation for DRS.

Resources: 
* [Data Repository Service 1.2.0](https://ga4gh.github.io/data-repository-service-schemas/preview/release/drs-1.2.0/docs/)

We also need to come up with a plan how to translate our file URLs/URIs to drs:// IDs.

**Comment by ReneRanzinger** [comment]
For the GA4GH meeting, virtual registration can be done here:

[https://broadinstitute.swoogo.com/ga4ghaprilconnect23/](https://broadinstitute.swoogo.com/ga4ghaprilconnect23/begin?i=HKDdETN7CkyM0SeTrXzRvbJ-SHq8gHwh)

and there is a document that describes the DRS-test-athon and further documentation here:

https://docs.google.com/document/d/10oSBnm3k7Cm3z-bw4JndR3Et7Zd62-st/edit?pli=1#



The GitHub repository for the HMP Node.js implementation can be found at:

https://github.com/ihmpdcc/drs-server


Finally, the Swagger documentation referenced in our meeting (albeit for version 1.1.0 of the spec) can be found at:

https://editor.swagger.io/?url=https://ga4gh.github.io/data-repository-service-schemas/preview/release/drs-1.1.0/swagger.yaml


Please let me know if you have any questions.

**Comment by senaarpinar** [comment]
implemented the drs server.  Tested with [drs-compliance-suite](https://github.com/ga4gh/drs-compliance-suite) and [drs-client](https://github.com/ga4gh/ga4gh-drs-client)

The DRS server required some changes to the stored files in the repository. Therefore, only the newly added files would be searchable. One example DRS object_id for testing is "1689791629481" (ggarray server).

**Comment by senaarpinar** [comment]
For Testing (ggarray)
DRS URL: drs://glygen.ccrc.uga.edu/ggarray/api/1689791629481
Dataset ID: AD5285063

**Comment by ReneRanzinger** [comment]
We needed to update the proxy to support "pathless" URIs:

drs://glygen.ccrc.uga.edu/1689791629481
