### ISSUE TITLE
Add wiki page for GlyTouCan, GLyCosmos, GlycoNAVI API usage

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#80]
Add a wiki page that documents the APIs we are using in:
* GlyTouCan
* GlyCosmos
* GlycoNAVI

and the functionality we use them for:
* Get GlyTouCan ID for WURCS, GlycoCT
* Convert glycan sequences (if we are not using the libraries)
* Submit new WURCS, GlycoCT sequence for registration
* Test GlyTouCan ID based on HASH
* Retrieve WURCS, GlycoCT with GlyTouCan ID
* (am I missing something)

Also document input and output or link existing online documentation (e.g. Swagger).

We could add this page here, in the gws2xlsx repository or any other place.

**Comment by senaarpinar** [comment]
@ReneRanzinger Added the Wiki page [Glytoucan API usage](https://github.com/glygener/glygen-array-backend/wiki/Glytoucan-API-usage)

I don't know of any API to get Glytoucan ID based on HASH. We use retrieval service to check if the glycan has been assigned a Glytoucan ID after registering.
