### ISSUE TITLE
Changes to multisheet metadata export

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#85]
Sheet "DatasetInfo"
* Change export options to use this format "Mirage Only: no; Single Sheet: no"
* Make the Keywords a single line with coma separated list
* Only have "Publication" in column A for the first paper
* Column width: A=25; B-E:30

Metadata sheets:
* Have space before and after "-" that is between type and name in the sheet label and the first row
* Add sample name in the sample sheet label and first row: "Sample - {sample name}"
* For the colspan row 1 use background color 255,255,204
* In row 2 (colspan 5, Word wrap) can we copy the text from the MIRAGE document where appropriate; background color 255,255,230
* Row 3 (currently 2) colspan 3 (A-C); Label: Information; Align center; Column width for A-C: 20
* Column D: width 60; Word wrap
* Column E,F: width 10
* Header for F: MIRAGE

**Comment by senaarpinar** [comment]
@ReneRanzinger for the text to be copied from MIRAGE document, do you mean the headline only or the description as well?
For example, this is for the Sample:

1. Sample: Glycan Binding Sample
A wide variety of samples can be applied to glycan microarrays. Here we use the term ‘Glycan
Binding Sample’ [‘Sample’] for a protein, a microorganism or other molecule being analysed for
carbohydrate recognition. Samples may include but are not restricted to glycan binding proteins (such
as lectins, antibodies, adhesion molecules, and carbohydrate-binding modules), glycan binding
organisms (such as viruses, fungi, bacteria, and animal cells), and other binding systems that may
have affinity for glycans including aptamers, or other synthetic glycan binding molecules.

**Comment by ReneRanzinger** [comment]
**Sample**
A wide variety of samples can be applied to glycan microarrays. Here we use the term ‘Glycan Binding Sample’ [‘Sample’] for a protein, a microorganism or other molecule being analysed for carbohydrate recognition. Samples may include but are not restricted to glycan binding proteins (such as lectins, antibodies, adhesion molecules, and carbohydrate-binding modules), glycan binding organisms (such as viruses, fungi, bacteria, and animal cells), and other binding systems that may have affinity for glycans including aptamers, or other synthetic glycan binding molecules.

**Slide**
A wide variety of solid phases can be used to print glycan microarrays. The utility of the data generated from a glycan array analysis will be related to the quality of the printed array.

**Printer**
Glycan microarrays are printed using a robotic liquid delivery system to deposit glycans on a printing surface. The utility of the data generated will be related to the quality of the printed array.

**Print-run**
Indicate the composition of the printing solution and the concentration of the glycan in the printing solution (single or more than one concentration). The physical conditions reported for array production should include temperature, humidity, reaction time for covalent coupling or adsorption, and post reaction treatment if applicable.

**Image processing**
Describe the software used to analyse (quantify) the output scanner image, indicating the name, version and manufacturer used and any special features active in the software (i.e. data smoothing, normalization, etc.).

**Scanner**
The most common detection method currently used for glycan microarray analysis is microscope slide fluorescence scanning, and there are several commercial instruments available for this type of analysis. Glycan microarrays can be printed in a variety of other formats including microtiter plate, and possibly in other geometries in custom instruments. In addition, a variety of detection methods are possible including surface plasmon resonance (SPR) and MS readouts and more precise or more sensitive detection may be developed in the future. 

**Data processing**
Provide details of how data in the table of microarray binding results are generated and calculated, i.e., specific software, normalization method, data selection procedures, and parameters, statistical analysis (including how the data from glycan replicates on the array were handled in the statistical method), transformation algorithm and scaling parameters.

**Comment by ReneRanzinger** [comment]
For sample please also make sure  the sample type is in the spreadsheet (e.g., protein, antibody)

**Comment by senaarpinar** [comment]
what about Assay Metadata?

**Comment by ReneRanzinger** [comment]
**Assay**
The protocol used for microarray binding analysis of Sample should include Sample concentration. Describe the composition of solutions, time and temperature used for blocking (preventing non-specific binding) binding, and washing, as well as application of secondary reagent(s) required for the analyses. If the Sample is precomplexed with secondary detection reagents prior to adding to the array (e.g. anti-His antibody with his-tagged Sample) give the ratio of reactants and pre-complexing time and temperature.

**Comment by senaarpinar** [comment]
done

**Comment by ReneRanzinger** [comment]
@senaarpinar The wordwrap for the text lines below the headlines is not working. Its always just one line. For fields like "AA sequence" its working well. Is that a problem with colspan?

The sample information is missing the type.

**Comment by senaarpinar** [comment]
I added the sample type but forgot to regenerate the report
I could not make it wrap when there is a colspan. If I find a way, I can fix the publication as well
