### ISSUE TITLE
Add usage of GlyTouCan web services

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#88]
In the wiki page with the [usage for GlyTouCan services](https://github.com/glygener/glygen-array-backend/wiki/Glytoucan-API-usage) add a headline in the end and link or projects (repository links) that are currently using any of these. Links to the actual Java files would be good if the functionally is not distributed over to many classes. Mark the one that need updating (e.g., using older services).

**Comment by senaarpinar** [comment]
added a section to list the java classes and parts that require updates
