### ISSUE TITLE
Process Akuls file

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#90]
Process @akulmehta file to build the master master list. Is there any array version that is completely resolved yet?
[GlycansFromLibrary_v3_AYM_JHM.xlsx](https://github.com/glygener/glygen-array-backend/files/11628102/GlycansFromLibrary_v3_AYM_JHM.xlsx)

**Comment by senaarpinar** [comment]
finished processing. There are 17 unresolved structures. I created a google sheet with these structures and copied Akul's comments as well. Here is the [document](https://docs.google.com/spreadsheets/d/1MbIuORIjRr4l02pJxRV_q0P3E8DMnMxP1fAEqu8L_lk/edit#gid=0)

**Comment by ReneRanzinger** [comment]
I need access for glycomics account (email). Please also share with @akulmehta. I think we ask him to do this. That might save him some and he only may have to edit the comments for Ryan.

**Comment by senaarpinar** [comment]
I changed it to "anyone with the link"

I also tried to see if there are versions completely resolved but so far, it looks like there are no such versions that do not include one of these 17 unresolved structures. We also have some typos etc in the processed data files that we need to fix even if all the master structure questions are resolved.
