### ISSUE TITLE
Collect a list of questions for Ryan

### ISSUE THREAD

**Issue by ReneRanzinger** [glygener/glygen-array-backend#91]
Review our old communication and collect a list of open questions for Ryan. Use a google doc/sheet.

**Comment by senaarpinar** [comment]
Here is the document summarizing the questions and links to the spreadsheets.

https://docs.google.com/document/d/1UJMB04CrXn4s1ZvUTe4_UsDnfq746Z_kOlxBjOfDM74/edit#heading=h.s8v320qdzzgg

@ReneRanzinger Can you have a look and add necessary details/explanations?

**Comment by ReneRanzinger** [comment]
I went over it didnt you also have some open questions regarding linkers or are they all resolved?

**Comment by senaarpinar** [comment]
@ReneRanzinger Do you mean the linkers without a pubchem id?

**Comment by ReneRanzinger** [comment]
Yes.

**Comment by senaarpinar** [comment]
@ReneRanzinger  Here is a link to the current linkers information. 
https://docs.google.com/spreadsheets/d/1e_g89k6zRCKlqawLbkOB71y-sMhMid-oSFunJfPD7CQ/edit#gid=0

Our last communication regarding this file:

"It lists all CFG linkers and their pubchem/SMILES when applicable. We have added a column to enter SMILES with glycan and surface positions. We will need that column to be filled if possible and also need SMILES/Pubchem or something similar for the ones missing that info"

I believe we have either pubchem or smiles (or both) for all linkers now but we may need to confirm if these assignments are correct.
