### ISSUE TITLE
'Other' option in the protein tag pull-down menu

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-backend#97]
**Is your feature request related to a problem? Please describe.**
It will be nice to have an 'other' option in the pull-down menu of the tag section of Glycan binding protein.
For example, if the user would like to indicate 'murine Fc-tag' or 'human Fc-tag', they can just write down in the other option

**Page**
Sample -> Protein -> Tag

**Comment by senaarpinar** [comment]
I believe there is a problem while editing an existing sample that prevents showing "other tag" option. If you add the "Tag" descriptor by selecting from the pull-down menu, it does not show these options.
