### ISSUE TITLE
[Request] Please add 'other' option in the Grant information (under Experiment)

### ISSUE THREAD

**Issue by yukie-a** [glygener/glygen-array-backend#99]
**Is your feature request related to a problem? Please describe.**
We would like to add the grant information such as Wellcome Trust and Medical Research Council, but there are not included in the pull-down menu (Funding Organization). 

**Describe the solution you'd like**
Could you please add Wellcome Trust (WT) and Medical Research Council (MRC), and also 'other' option?

**Page**
Experiment -> under 'Grants' section.

**Comment by ReneRanzinger** [comment]
If other is selected a free text input field should be shown. That should not change the datamodel since both are strings, but is there any server side code that might prevent this?

**Comment by senaarpinar** [comment]
I added "Other" option to the funding organizations list. The frontend was already implemented to handle "other" option.
